name: Actions Workflow

on:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-22.04
    steps:
      # By default GH does not clone our repository list of files will be empty
      - name: List Files
        run: |
          pwd
          ls -la
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: List Files after checkout and echo automatic variables
        run: |
          pwd
          ls -la
          # Commit that triggered workflow
          echo "GITHUB SHA is : ${GITHUB_SHA}"
          echo "GITHUB_REF is : ${GITHUB_REF}"
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          # Access Token that was used to access workflow repository
          echo "${{ github.token }}"
          # Clone to subdir using variables
          git clone https://${{ github.token }}@github.com/${GITHUB_REPOSITORY}.git ./tmpdir
          # git clone git@github.com:$GITHUB_REPOSITORY ./tmpdir
          # Checkout to commit that triggered workflow
          cd ./tmpdir
          # git checkout $GITHUB_SHA
          ls -la
      - name: Simple JS Actions
        id: greet
        # username/repository-name@reference (like tag)
        uses: actions/hello-world-javascript-action@v1.1
        # Use commit for referencing action
        # uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        # Use branch name
        # uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: Radoslaw Cisz
      - name: Log Greeting Time from action
        run: echo "${{ steps.greet.outputs.time }}"