name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-22.04
    steps:
      - name: List Files
        run: |
          pwd
          ls -l
      - name: Simple JS Actions
        id: greet
        # username/repository-name@reference (like tag)
        uses: actions/hello-world-javascript-action@v1.1
        # Use commit for referencing action
        # uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
        # Use branch name
        # uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: Radoslaw Cisz
      - name: Log Greeting Time from action
        run: echo "${{ steps.greet.outputs.time }}"