name: Containers
on: [push]

jobs:
  docker-steps:
    runs-on: ubuntu-22.04
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node version
        run: node --version
      - name: Step with Dockerfile
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          #  An array of strings is not supported by this parameter.
          args: The ${{ github.event_name }} event triggered this step.
      - name: Step with Dockerfile
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /usr/local/bin/node
          args: --version
  node-docker:
    runs-on: ubuntu-22.04
    container:
      image: node:18-buster-slim
      env:
        MY_ENV_VAR: "true"
      # ports:
      # volumes:
      # options: --cpus 1 --host ...
    steps:
    - name: Log node version
      run: node --version