name: Manual Dispatch Workflow
on:
  repository_dispatch:
    types: [on-demand-run]


jobs:
  run-shell-command:
    runs-on: ubuntu-22.04
    steps:
      - name: Hello From Step
        run: |
          echo "Hello From Step"
      - name: Retrive Client Payload
        run: |
          echo ${{ github.event.client_payload.env }}
      - name: Display Full github event
        run: |
          echo ${{ github.event }}