name: Shell Commands
on:
  push:
    branches:
      - main
      - 'feature/*' # does not match feature/cos/cos
      - 'feature/**' # does match feature/cos/cos
      - '!feature/featC' # Ignore this branch (has to be added after main patterns)
    # branches-ignore:
    #   - 'bug/*'
    tags:
      - v1.1
    # tags-ignore:
    #   - "v0.1"
    paths:
      - '**.js' # runs only when js file is changed
      - '!filename.js' # ignore this file
    # paths-ignore:
    #   - "**.md"
    #   - 'docs/**'

  schedule:
    - cron: "12 10 21 7 *"

jobs:
  run-shell-command:
    timeout-minutes: 360
    runs-on: ubuntu-22.04
    steps:
      - name: echo a string
        run: echo "Hello From Workflow"
        # Continue all other steps on error
        continue-on-error: true
        timeout-minutes: 30
      - name: multiline script
        run: |
          node -v
          python --version
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-2019
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Direcotry Bash
        run: pwd
        shell: bash