name: Simple API
on: [push]

jobs:
  test-simple-api:
    runs-on: ubuntu-22.04
    # By default it is in bridge network with hostnames reachable
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: |
          curl -X POST http://localhost:3001/api/user -H "Content-Type: application/json" -d '
          {\"username\": \"Joe Doe\", \"address\": \"Some Address\"}'
      - name: Get users list
        run: |
          curl -X GET http://localhost:3001/api/users
