name: Strategy exercices

on: [push]

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [12,14,16]
        os: [ubuntu-22.04, macos-latest]
        exclude:
          - os: macos-latest
            node_version: 12
        # add extra values/attributes to job that already exists in our matrix
        include:
          - os: macos-latest
            node_version: 16
            is_macos_16: "true"
      # fail-fast: true
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Node Action
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: |
          echo "Running on ${{ matrix.os }}"
          node --version
          echo "IS_MACOS_AND_16: ${IS_MACOS_AND_16}"
        env:
          IS_MACOS_AND_16: ${{ matrix.is_macos_16 }}

